### PR TITLE
Refactor: Replace Platform (dart:io) with TargetPlatform

### PR DESCRIPTION
**Pull request by AmosHuKe**
## Related issues (optional)

None.

## Description

Support WASM.
image

## Summary (check all that apply)

- [x] Modified / added code
- [x] Modified / added tests
- [x] Modified / added examples
- [ ] Modified / added others (pubspec.yaml, workflows, etc...)
- [ ] Updated README
- [ ] Contains breaking changes
  - [ ] Created / updated migration guide
- [ ] Incremented version number
  - [ ] Updated CHANGELOG

### CODE REVIEW

**Comment by fujidaiti** [comment]
Hi @AmosHuKe, thank you for your contribution.
It LGTM, but it seems that you committed to the wrong branch. Could you rebase the PR onto the main branch?

**Comment by AmosHuKe** [comment]
@fujidaiti 
I was originally hoping to use it with Flutter 3.24.x, so I pushed it to this branch.
Do I need another PR for the main branch?

**Comment by fujidaiti** [comment]
@AmosHuKe 
You can rebase the PR as follows:
```console
git checkout refactor-platform
git rebase --onto main v1.0.0-f324.x refactor-platform
```

**Comment by AmosHuKe** [comment]
@fujidaiti Is this right?

**Comment by fujidaiti** [comment]
Hmm, something still went wrong… I’ll check it out.

**Comment by AmosHuKe** [comment]
😂😂😂 Do I need to PR again? (close this and rebase it on the main branch, commit to main)

**Comment by fujidaiti** [comment]
@AmosHuKe That might be better, if you don't mind :)

**Pull request closed without merging**
